language: go

go:
  - 1.8.x


install: go get -v ./...

script: go build -v -o $TRAVIS_BUILD_DIR/rbacq

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file: $TRAVIS_BUILD_DIR/rbacq
  skip_cleanup: true
  on:
    tags: true
