language: go

go:
  - 1.8.x

install: go get -v ./...

before_script: chmod +x $TRAVIS_BUILD_DIR/travis-build.sh

script: $TRAVIS_BUILD_DIR/travis-build.sh

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
    - $TRAVIS_BUILD_DIR/rbacq
    - $TRAVIS_BUILD_DIR/rbacq.exe
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
